name: My First Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Build Coding Practice"

      - name: Copy files to server using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}     
          port: 22
          source: "./"
          target: "/home/ubuntu/app"
          timeout: 30s
          command_timeout: 10m

      - name: Invoke Jenkins Deployment Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://3.110.233.187:8080"
          user: "labuser"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "Tomcat Deployment"
