

name: My First Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
   
      - name: Build
        run: echo "Build Coding Practice"
      
      - name: Invoke Jenkins Deployment Job
        uses: appleboy/jenkins-action@master
        with:
            url: "http://3.110.233.187:8080"
            user: "admin"
            token: ${{ secrets.JENKINS_TOKEN }}
            job: "Tomcat Deployment"
